// src/tripData/Expense.vue
<script setup lang="ts">
import type { TripExpense } from "@/api/expense";
import { format } from "date-fns";
import { computed } from "vue";
import ExpenseCategoryIcon from "./ExpenseCategoryIcon.vue";

const { expense } = defineProps<{
  expense: TripExpense;
}>();

const emit = defineEmits<{
  (e: "click"): void;
}>();

const date = computed(() => new Date(expense.localDateTime));
const expenseTime = computed(() => format(date.value, "HH:mm"));
const expenseDay = computed(() => format(date.value, "do"));
const expenseMonth = computed(() => format(date.value, "MMM"));
const userInitals = computed(() => {
  const firstNameLetter = expense.user.firstName.slice(0, 1).toUpperCase();
  const lastNameLetter = expense.user.lastName.slice(0, 1).toUpperCase();
  return `${firstNameLetter}${lastNameLetter}`;
});
const isUnsavedExpense = computed(() => expense.id < 0);
</script>

<template>
  <div
    :data-expense-id="expense.id"
    class="flex border-t border-b border-l even:border-t-0 even:border-b-0 border-solid border-gray-300 cursor-pointer hover:bg-gray-200"
    @click="emit('click')"
  >
    <div
      class="flex px-1 py-1 text-white border-b border-solid border-white"
      :class="{
        'bg-primary': !isUnsavedExpense,
        'bg-amber-500': isUnsavedExpense,
      }"
    >
      <div class="flex h-full flex-col items-center justify-center w-16">
        <span class="font-bold text-sm"> {{ expenseDay }} {{ expenseMonth }} </span>
        <span class="text-xs">{{ expenseTime }}</span>
      </div>
    </div>
    <div class="flex flex-1 flex-col p-2 flex-nowrap overflow-hidden">
      <div class="flex items-center w-full flex-nowrap">
        <fa-icon :icon="['fas', 'location-dot']" class="text-gray-800" />
        <span class="ml-2 whitespace-nowrap text-ellipsis overflow-hidden font-semibold">
          {{ expense.city.name }}
        </span>
      </div>
      <div class="mt-1 flex items-center w-full flex-nowrap">
        <ExpenseCategoryIcon :category-id="expense.category.id" />
        <span class="ml-2 whitespace-nowrap text-ellipsis overflow-hidden">
          {{ expense.category.name }}
        </span>
      </div>
    </div>
    <div class="flex items-center justify-center px-4">
      <span class="font-bold"><span v-if="!isUnsavedExpense">€</span>{{ expense.euroAmount }}</span>
    </div>
    <div
      class="flex items-center justify-center w-10"
      :class="{
        'bg-primary': !isUnsavedExpense,
        'bg-amber-500': isUnsavedExpense,
      }"
    >
      <span class="text-white font-bold">{{ userInitals }}</span>
    </div>
  </div>
</template>

// src/components/Expense/Expense.tsx
// import { PATHS } from "@/router";
// import { Link } from "react-router-dom";
import format from "date-fns/format";
import { useMemo } from "react";
import { ExpenseProps } from "./Expense.types";

export default function Expense({ expense, onClick }: ExpenseProps) {
  const formattedDate = useMemo(() => {
    return format(new Date(expense.localDateTime), "do MMM HH:mm");
  }, [expense]);

  return (
    <>
      {expense.isSaved && (
        <tr
          className="hover cursor-pointer select-none"
          onClick={() => onClick(expense.id)}
        >
          <td></td>
          <td>{formattedDate}</td>
          <td>{expense.category.name}</td>
          <td align="center">€{expense.euroAmount}</td>
          <td align="center">{expense.city.name}</td>
          <td align="center">
            {expense.amount} {expense.currency.code}
          </td>
          <td className="px-4">{expense.user.firstName}</td>
        </tr>
      )}
      {!expense.isSaved && (
        <tr
          className="hover cursor-pointer select-none"
          onClick={() => onClick(expense.id)}
        >
          <td className="bg-rose-400"></td>
          <td className="bg-rose-400">{formattedDate}</td>
          <td className="text-ellipsis overflow-hidden bg-rose-400">
            {expense.category.name}
          </td>
          <td align="center" className=" bg-rose-400">
            {expense.euroAmount}
          </td>
          <td className="text-ellipsis overflow-hidden bg-rose-400">
            {expense.city.name}
          </td>
          <td align="center" className="bg-rose-400">
            {expense.amount} {expense.currency.code}
          </td>
          <td className="px-4 bg-rose-400">{expense.user.firstName}</td>
        </tr>
      )}
    </>
  );
}
