// src/components/Modals/ConfirmModal/ConfirmModal.tsx
import Modal from "../ModalBase/Modal";
import ModalBody from "../ModalBase/ModalBody";
import ModalFooter from "../ModalBase/ModalFooter";

export interface ConfirmModalProps {
  title: React.ReactNode;
  onConfirm: (isConfirmed: boolean) => void;
}

export function ConfirmModal({ title, onConfirm }: ConfirmModalProps) {
  return (
    <Modal position="center">
      <ModalBody height="auto">
        <div className="pt-8">{title}</div>
      </ModalBody>
      <ModalFooter>
        <button
          className="btn btn-secondary font-bold text-md mr-4"
          onClick={() => onConfirm(false)}
        >
          No
        </button>
        <button
          className="btn btn-error font-bold text-md"
          onClick={() => onConfirm(true)}
        >
          Yes
        </button>
      </ModalFooter>
    </Modal>
  );
  return (
    <div className="et-modal-backdrop">
      <div className="animate-fade-in et-modal overflow-hidden box-content z-40">
        <div className="mb-2">{title}</div>
        <div className="flex justify-end items-center pt-6">
          <button
            className="btn btn-secondary font-bold text-md mr-4"
            onClick={() => onConfirm(false)}
          >
            No
          </button>
          <button
            className="btn btn-error font-bold text-md"
            onClick={() => onConfirm(true)}
          >
            Yes
          </button>
        </div>
      </div>
    </div>
  );
}

// src/modal/ConfirmModal.vue
<script setup lang="ts">
const { title, type } = defineProps<{
  title: string;
  type?: "danger" | "warning";
}>();

const slots = defineSlots<{
  body(): any;
}>();

const emit = defineEmits<{
  (e: "confirm"): void;
  (e: "cancel"): void;
}>();
</script>

<template>
  <Teleport to="body">
    <div class="et-modal-backdrop overflow-hidden">
      <div
        class="animate-slide-in-bottom et-modal et-modal--position-bottom overflow-hidden box-content w-[410px] p-0 absolute bottom-0 md:relative"
      >
        <div class="relative">
          <div
            class="flex justify-between items-center py-4 px-6 text-white rounded-t-2xl"
            :class="{
              'bg-sky-600': !type,
              'bg-amber-600': type === 'warning',
              'bg-rose-600': type === 'danger',
            }"
          >
            <h2 class="font-bold text-2xl">{{ title }}</h2>
          </div>

          <div class="flex flex-col overflow-scroll p-6">
            <slot name="body" />
          </div>

          <div class="flex pt-6 px-6 pb-4 flex-end">
            <div class="flex flex-1 justify-center">
              <button class="et-btn-secondary mr-4" @click="emit('cancel')">Cancel</button>
              <button
                class="et-btn text-white"
                :class="{
                  'et-btn-primary': !type,
                  'et-btn-danger': type === 'danger',
                  'et-btn-warning': type === 'warning',
                }"
                @click="emit('confirm')"
              >
                Confirm
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </Teleport>
</template>
