// src/components/Modals/AddCountryModal/AddCountryModal.tsx
import { loadCountries } from "@/api";
import Modal from "@/components/Modals/ModalBase/Modal";
import ModalBody from "@/components/Modals/ModalBase/ModalBody";
import ModalFooter from "@/components/Modals/ModalBase/ModalFooter";
import ModalHeader from "@/components/Modals/ModalBase/ModalHeader";
import type { PickerOption } from "@/components/widgets/Picker/Picker";
import Picker from "@/components/widgets/Picker/Picker";
import { useCallback, useEffect, useState } from "react";
import type { TripModalCountry } from "../TripModalHOC/TripModalHOC";
import CityPickerList, { OnClickCityProps } from "./CityPickerList";

export interface AddCountryModalProps {
  onClose: () => void;
  onSave: (country: TripModalCountry) => void;
  initalData: TripModalCountry | null;
}

export default function AddCountryModal({
  onClose,
  onSave,
  initalData,
}: AddCountryModalProps) {
  const [countryPickerOptions, setCountryPickerOptions] = useState<
    PickerOption[]
  >([]);

  const [selectedCountryId, setSelectedCountryId] = useState(
    initalData?.countryId || 0
  );
  const [selectedCityIds, setSelectedCityIds] = useState<number[]>(
    initalData?.cityIds ?? []
  );

  const onSelectCity = useCallback(
    ({ op, cityId }: OnClickCityProps) => {
      if (op === "remove") {
        setSelectedCityIds(selectedCityIds.filter((id) => id !== cityId));
      }

      if (op === "add") {
        setSelectedCityIds([...selectedCityIds, cityId]);
      }
    },
    [selectedCityIds]
  );

  const onSelectCountry = useCallback((countryId: number) => {
    setSelectedCountryId(countryId);
  }, []);

  const onClickCancel = useCallback(() => {
    onClose();
  }, [onClose]);

  const onClickSave = useCallback(() => {
    const data: TripModalCountry = {
      countryId: selectedCountryId,
      name: countryPickerOptions.find((c) => c.value === selectedCountryId)!
        .label,
    };

    if (selectedCityIds.length) {
      data.cityIds = selectedCityIds;
    }

    onSave(data);
    onClose();
  }, [
    countryPickerOptions,
    onClose,
    onSave,
    selectedCityIds,
    selectedCountryId,
  ]);

  useEffect(() => {
    loadCountries().then((countries) => {
      setCountryPickerOptions(
        countries.map((c) => ({
          value: c.id,
          label: c.name,
        }))
      );
    });
  }, []);

  return (
    <Modal>
      <ModalHeader title="Add a Country" />
      <ModalBody>
        <div className="flex flex-col py-4">
          <span className="mb-4 font-bold">Pick a country</span>
          <Picker
            options={countryPickerOptions}
            value={selectedCountryId}
            onChange={onSelectCountry}
            isMulti={false}
          />
        </div>
        {selectedCountryId > 0 && (
          <div className="flex flex-col py-4">
            <CityPickerList
              countryId={selectedCountryId}
              cityIds={selectedCityIds}
              onSelectCity={onSelectCity}
            />
          </div>
        )}
      </ModalBody>
      <ModalFooter>
        <button
          className="btn btn-secondary font-bold text-md mr-4"
          onClick={onClickCancel}
        >
          Cancel
        </button>
        <button
          className="btn btn-primary font-bold text-md"
          onClick={onClickSave}
        >
          Save
        </button>
      </ModalFooter>
    </Modal>
  );
}

// src/trips/AddCountryModal.vue
<script setup lang="ts">
import Modal from "@/modal/Modal.vue";
import Picker from "@/pickers/Picker.vue";
import { computed, ref } from "vue";
import type { TripModalCountry } from "./AddTripModal.vue";
import CityPickerList from "./CityPickerList.vue";
import useAddCountryModalOptions from "./hooks/useAddCountryModalOptions";

const { countrySelectionToEdit } = defineProps<{
  countrySelectionToEdit?: Nullable<TripModalCountry>;
}>();

const emit = defineEmits<{
  (e: "close"): void;
  (e: "save", country: TripModalCountry): void;
}>();

const { countryOptions } = useAddCountryModalOptions();

const selectedCountryId = ref<Nullable<number>>(countrySelectionToEdit?.countryId ?? null);
const selectedCityIds = ref<number[]>(countrySelectionToEdit?.cityIds ?? []);

const selectedCountry = computed(() =>
  countryOptions.value.find((c) => c.value === selectedCountryId.value),
);

const onClickSave = () => {
  if (!selectedCountry.value) return;

  const data: TripModalCountry = {
    name: selectedCountry.value.label,
    countryId: selectedCountry.value.value,
    cityIds: selectedCityIds.value,
  };

  emit("save", data);
  emit("close");
};
</script>

<template>
  <Modal title="Add a Country">
    <template v-slot:body>
      <div class="flex flex-col py-4">
        <span class="mb-4 font-bold">Pick a country</span>
        <Picker :options="countryOptions" v-model="selectedCountryId" />
      </div>
      <div v-if="selectedCountryId" class="flex flex-col py-4">
        <CityPickerList :countryId="selectedCountryId" v-model="selectedCityIds" />
      </div>
    </template>

    <template v-slot:footer>
      <button class="btn btn-secondary font-bold text-md mr-4" @click="emit('close')">
        Cancel
      </button>
      <button
        class="btn btn-primary font-bold text-md"
        :disabled="!selectedCountry"
        @click="onClickSave"
      >
        Save
      </button>
    </template>
  </Modal>
</template>
