// src/components/Modals/AddCountryModal/CityPickerList.tsx
import { City as CityType, loadCitiesForCountry } from "@/api";
import { useCallback, useEffect, useMemo, useState } from "react";
import City from "./City";
import SelectedCitiesPopUp from "./SelectedCitiesPopup";

export interface OnClickCityProps {
  op: "add" | "remove";
  cityId: number;
}

export interface CityPickerListProps {
  countryId: number;
  cityIds: number[];
  onSelectCity: ({ op, cityId }: OnClickCityProps) => void;
}

export default function CityPickerList({
  countryId,
  onSelectCity,
  cityIds: selectedCityIds,
}: CityPickerListProps) {
  const [cities, setCities] = useState<Omit<CityType, "timezoneName">[]>([]);
  // const [selectedCityIds, setSelectedCityIds] = useState<number[]>(cityIds);
  const [isSelectedCitiesPopupOpen, setIsSelectedCitiesPopupOpen] =
    useState(false);
  const [searchTerm, setSearchTerm] = useState("");

  const citiesToDisplay = useMemo(() => {
    if (searchTerm) {
      return cities.filter((city) => {
        return city.name.toLowerCase().includes(searchTerm.toLowerCase());
      });
    }

    return cities;
  }, [searchTerm, cities]);

  const selectedCities = useMemo(() => {
    return selectedCityIds.map((id) => cities.find((city) => city.id === id)!);
  }, [selectedCityIds, cities]);

  const loadCityOptions = async () => {
    const cities = await loadCitiesForCountry(countryId);
    setCities(cities);
  };

  const onClickCity = useCallback(
    (cityId: number) => {
      if (selectedCityIds.includes(cityId)) {
        onSelectCity({ op: "remove", cityId });
      } else {
        onSelectCity({ op: "add", cityId });
      }
    },
    [onSelectCity, selectedCityIds]
  );

  useEffect(() => {
    setCities([]);
    loadCityOptions();
    setSearchTerm("");
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [countryId]);

  return (
    <div className="flex flex-col">
      <span className="mb-2 font-bold">Pick the cities you will visit</span>
      <span className="mb-2 text-sm">
        If you dont select any you will be able to choose any of them when
        adding an expense.
      </span>
      <div className="my-2">
        <input
          type="search"
          className="w-full p-2 rounded bg-white border border-solid border-gray-200"
          placeholder="Search for a city"
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
        />
      </div>
      <div className="flex justify-between flex-wrap h-[180px] overflow-scroll">
        {citiesToDisplay.length === 0 && searchTerm && (
          <span>No cities match your search term</span>
        )}
        {citiesToDisplay.map((city) => {
          const isSelected = selectedCityIds.includes(city.id);
          return (
            <div className="w-1/2" key={city.id}>
              <City city={city} isSelected={isSelected} onClick={onClickCity} />
            </div>
          );
        })}
      </div>
      <div className="mt-6 flex justify-center">
        {selectedCityIds.length > 0 && (
          <button
            className="underline"
            onClick={() => setIsSelectedCitiesPopupOpen(true)}
          >
            View Selected Cities
          </button>
        )}
      </div>
      {isSelectedCitiesPopupOpen && (
        <SelectedCitiesPopUp
          selectedCities={selectedCities}
          onClickCity={onClickCity}
          onClose={() => setIsSelectedCitiesPopupOpen(false)}
        />
      )}
    </div>
  );
}

// src/trips/CityPickerList.vue
<script setup lang="ts">
import Modal from "@/modal/Modal.vue";
import { computed, ref, toRefs } from "vue";
import City from "./City.vue";
import useCityOptions from "./hooks/useCityOptions";

const props = defineProps<{
  countryId: number;
}>();

const { countryId } = toRefs(props);

const selectedCityIds = defineModel<number[]>({ default: [] });

const searchTerm = ref("");
const isViewSelectedCitiesModalOpen = ref(false);

const { cityOptions } = useCityOptions(countryId, searchTerm);

const selectedCities = computed(() => {
  return selectedCityIds.value.map(
    (id) => cityOptions.value.find((option) => option.value === id)!,
  );
});

const onClickCity = (cityId: number) => {
  const existingItemIdx = selectedCityIds.value.indexOf(cityId);
  if (existingItemIdx > -1) {
    selectedCityIds.value.splice(existingItemIdx, 1);
  } else {
    selectedCityIds.value.push(cityId);
  }
};

const toggleViewSelectedCitiesModal = () => {
  isViewSelectedCitiesModalOpen.value = !isViewSelectedCitiesModalOpen.value;
};
</script>

<template>
  <div class="flex flex-col">
    <span class="mb-2 font-bold">Pick the cities you will visit</span>
    <span class="mb-2 text-sm">
      If you dont select any you will be able to choose any of them when adding an expense.
    </span>
    <div class="my-2">
      <input
        type="search"
        class="w-full p-2 rounded bg-white border border-solid border-gray-200"
        placeholder="Search for a city"
        v-model="searchTerm"
      />
    </div>
    <div class="mt-4 flex justify-between flex-wrap max-h-[150px] overflow-scroll pr-4">
      <span v-if="!cityOptions.length && searchTerm">No cities match your search term</span>

      <div v-if="cityOptions.length" class="grid grid-cols-3 gap-x-2 gap-y-4">
        <City
          v-for="city in cityOptions"
          :key="city.value"
          :city="city"
          :is-selected="selectedCityIds.includes(city.value)"
          :use-pill="true"
          @click="onClickCity"
        />
      </div>
    </div>

    <div class="mt-4 flex justify-center">
      <button
        v-if="selectedCityIds.length"
        class="underline"
        @click="toggleViewSelectedCitiesModal"
      >
        View Selected Cities
      </button>
    </div>

    <Modal
      v-if="isViewSelectedCitiesModalOpen"
      title="Selected Cities"
      :height="400"
      :include-close-button="true"
      @close="toggleViewSelectedCitiesModal"
    >
      <template v-slot:body>
        <div class="py-4 w-full">
          <span v-if="selectedCityIds.length === 0" class="text-center"
            >No cities have been selected.</span
          >

          <City
            v-for="city in selectedCities"
            :key="city.value"
            :city="city"
            :isSelected="true"
            :onClick="onClickCity"
          />
        </div>
      </template>
    </Modal>
  </div>
</template>
