// src/components/Modals/AddCountryModal/City.tsx
import { City as CityType } from "@/api";
import { ReactComponent as CheckIcon } from "@/assets/check.svg";

interface CityProps {
  city: Omit<CityType, "timezoneName">;
  isSelected: boolean;
  onClick: (cityId: number) => void;
}

export default function City({ city, isSelected, onClick }: CityProps) {
  return (
    <div
      className="flex items-center justify-between h-12 overflow-hidden px-2 py-4 hover:opacity-70 cursor-pointer"
      key={city.id}
      onClick={() => onClick(city.id)}
    >
      <span className={`truncate ${isSelected ? "text-green-600" : ""}`}>
        {city.name}
      </span>
      {isSelected && (
        <span className="ml-2">
          <CheckIcon className="w-6 fill-green-600" />
        </span>
      )}
    </div>
  );
}

// src/trips/City.vue
<script setup lang="ts">
import type { CityOption } from "./hooks/useCityOptions";

const { city, isSelected } = defineProps<{
  city: CityOption;
  isSelected: boolean;
  usePill?: boolean;
}>();

const emit = defineEmits<{
  (e: "click", id: number): void;
}>();
</script>

<template>
  <div
    class="flex items-center select-none h-12 overflow-hidden px-2 py-4 hover:opacity-70 cursor-pointer"
    :class="{
      'bg-grey-300 border border-solid border-black rounded-lg justify-center text-center': usePill,
      'border-green-600 bg-green-100': isSelected && usePill,
    }"
    @click="emit('click', city.value)"
  >
    <span :class="{ truncate: true, 'text-green-600': isSelected }">
      {{ city.label }}
    </span>
  </div>
</template>
