// src/components/sections/Header/Header.tsx
import { ReactComponent as Logo } from "@/assets/logo.svg";
import { PATHS } from "@/router";
import { Link } from "react-router-dom";
import Dropdown from "./DropdownMenu";

export default function Header({
  onClickSettings,
}: {
  onClickSettings: () => void;
}) {
  return (
    <div className="navbar bg-base-100 pb-4 min-h-20">
      <div className="navbar-start">
        <Link to={PATHS.HOME} className="p-2">
          <Logo className="w-32" />
        </Link>
      </div>
      <div className="navbar-end">
        <Dropdown onClickSettings={onClickSettings} />
      </div>
    </div>
  );
}

// src/app/Header.vue
<script setup lang="ts">
import Logo from "@/assets/logo.svg";
import { RouterLink } from "vue-router";
import UserDropdown from "./UserDropdown.vue";
</script>

<template>
  <div class="navbar bg-base-100 pb-4 min-h-20">
    <div class="navbar-start">
      <RouterLink to="/" class="p-2">
        <Logo class="w-32" />
      </RouterLink>
    </div>
    <div class="navbar-end">
      <UserDropdown />
    </div>
  </div>
</template>
