// src/components/Expense/Expense.tsx
// import { PATHS } from "@/router";
// import { Link } from "react-router-dom";
import format from "date-fns/format";
import { useMemo } from "react";
import { ExpenseProps } from "./Expense.types";

export default function Expense({ expense, onClick }: ExpenseProps) {
  const formattedDate = useMemo(() => {
    return format(new Date(expense.localDateTime), "dd-MM-yyyy HH:mm");
  }, [expense]);

  return (
    <>
      {expense.isSaved && (
        <tr
          className="hover cursor-pointer select-none"
          onClick={() => onClick(expense.id)}
        >
          <td>{formattedDate}</td>
          <td>
            {expense.category.name}
          </td>
          <td align="center">€{expense.euroAmount}</td>
          <td align="center">{expense.city.name}</td>
          <td align="center">{expense.amount} {expense.currency.code}</td>
          
        </tr>
      )}
      {!expense.isSaved && (
        <tr
          className="hover cursor-pointer select-none"
          onClick={() => onClick(expense.id)}
        >
          <td className="bg-rose-900">{formattedDate}</td>
          <td className="text-ellipsis overflow-hidden bg-rose-900">
            {expense.category.name}
          </td>
          <td className="text-ellipsis overflow-hidden bg-rose-900">
            {expense.city.name}
          </td>
          <td align="center" className=" bg-rose-900">
            {expense.euroAmount}
          </td>
        </tr>
      )}
    </>
  );
}

// src/components/trip/Expense.vue
<script setup lang="ts">
import type { TripExpense } from "@/api/expense";
import { MapPin } from "@lucide/vue";
import { format } from "date-fns";
import { computed } from "vue";
import AvatarGroup from "./AvatarGroup.vue";
import ExpenseCategoryIcon from "./ExpenseCategoryIcon.vue";

const { expense } = defineProps<{
  expense: TripExpense;
}>();

const emit = defineEmits<{
  (e: "click"): void;
}>();

const date = computed(() => new Date(expense.localDateTime));
const expenseTime = computed(() => format(date.value, "HH:mm"));
const isUnsavedExpense = computed(() => expense.id < 0);
</script>

<template>
  <div
    :data-testid="`expense-${expense.id}`"
    class="grid grid-cols-[1fr_3.5fr_0.5fr_1.25fr] gap-5 items-stretch border-b border-slate-700/50 py-2 cursor-pointer last:border-b-0"
    :class="{
      'bg-amber-700': isUnsavedExpense,
    }"
    @click="emit('click')"
  >
    <div class="flex items-center justify-center">
      <ExpenseCategoryIcon :category-id="expense.category.id" />
    </div>

    <div class="flex flex-col overflow-hidden">
      <div class="overflow-hidden text-ellipsis whitespace-nowrap text-sm">
        <span v-if="expense.description.trim()">{{ expense.description }}</span>
        <span v-else class="text-gray-500 italic">No description provided</span>
      </div>
      <div class="flex text-text-3 text-xs gap-3 pt-2">
        <div>
          {{ expenseTime }}
        </div>
        <div class="flex items-center"><MapPin class="mr-1 size-[10px]" /> {{ expense.city.name }}</div>
      </div>
    </div>

    <!-- Users (stacked initials) -->
    <div class="flex items-center justify-center">
      <AvatarGroup :users="expense.users" />
    </div>

    <div class="flex flex-col items-center justify-center">
      <div class="text-sm">€{{ expense.euroAmount }}</div>
      <div v-if="expense.currency.code !== 'EUR'" class="text-[9px]">
        {{ `${expense.amount} ${expense.currency.code}` }}
      </div>
    </div>
  </div>
</template>
